import { z } from "zod";
import { databaseError, supabase } from "../../db/supabase";
import { createTeamRecord, teamSchema } from "../api/teams/route";
import { createTaskRecord } from "../api/tasks/route";

type ToolResult = { success: boolean; error?: string; record?: Record<string, unknown> };
type ToolCall = { id: string; function?: { name?: string; arguments?: string } };
export const atlasTools = [
  { type: "function", function: { name: "create_task", description: "Creates a personal or team task.", parameters: { type: "object", properties: { title: { type: "string" }, due_date: { type: "string" }, priority: { type: "string", enum: ["urgent", "high", "medium", "low"] }, team_name: { type: "string" } }, required: ["title"] } } },
  { type: "function", function: { name: "checkin_habit", description: "Marks a habit complete for today.", parameters: { type: "object", properties: { habit_name: { type: "string" } }, required: ["habit_name"] } } },
  { type: "function", function: { name: "assign_task_to_team", description: "Assigns an existing task to a council team.", parameters: { type: "object", properties: { task_title: { type: "string" }, team_name: { type: "string" } }, required: ["task_title", "team_name"] } } },
  { type: "function", function: { name: "create_team", description: "Creates a new team in the council structure.", parameters: { type: "object", properties: { name: { type: "string" }, description: { type: "string" } }, required: ["name"] } } },
] as const;
const createTask = z.object({ title: z.string().trim().min(1, "A task title is required").max(200), due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), priority: z.enum(["urgent", "high", "medium", "low"]).default("medium"), team_name: z.string().trim().max(100).optional() });
const checkinHabit = z.object({ habit_name: z.string().trim().min(1, "A habit name is required").max(200) }); const assignTask = z.object({ task_title: z.string().trim().min(1).max(200), team_name: z.string().trim().min(1).max(100) }); const createTeam = z.object({ name: z.string().trim().min(1).max(100), description: z.string().trim().max(2000).default("") });
async function findTeam(client: ReturnType<typeof supabase>, wanted: string) { const { data, error } = await client.from("teams").select("id,name").eq("archived", false); if (error) throw databaseError(error, "Unable to load teams"); const needle = wanted.toLowerCase().replace(/\b(the|team)\b/g, "").trim(); const match = (data ?? []).find((team) => { const name = String(team.name).toLowerCase(); return name === needle || name.includes(needle) || needle.includes(name); }); return { team: match, names: (data ?? []).map((team) => String(team.name)) }; }
async function runCreateTask(input: unknown): Promise<ToolResult> { const p = createTask.safeParse(input); if (!p.success) return { success:false,error:p.error.issues[0]?.message || "Invalid task" }; const client=supabase(); let team=""; if(p.data.team_name){const found=await findTeam(client,p.data.team_name);if(!found.team)return{success:false,error:`No matching team. Choose: ${found.names.join(", ")}.`};team=String(found.team.name)} const task=await createTaskRecord({title:p.data.title,dueDate:p.data.due_date||"",priority:p.data.priority,team,goalId:null});const{data:verified,error:verifyError}=await client.from("tasks").select("id,title,team_id").eq("id",task.id).eq("archived",false).maybeSingle();if(verifyError)throw databaseError(verifyError,"Unable to verify task");return verified?{success:true,record:verified as Record<string,unknown>}:{success:false,error:"The task could not be verified after creation."}; }
async function runHabit(input:unknown):Promise<ToolResult>{const p=checkinHabit.safeParse(input);if(!p.success)return{success:false,error:p.error.issues[0]?.message||"Invalid habit"};const c=supabase();const{data:habit,error}=await c.from("habits").select("id,name").ilike("name",p.data.habit_name).eq("archived",false).maybeSingle();if(error)throw databaseError(error,"Unable to find habit");if(!habit)return{success:false,error:`Habit \"${p.data.habit_name}\" was not found.`};const date=new Date().toISOString().slice(0,10);const{error:write}=await c.from("habit_checkins").upsert({habit_id:habit.id,completed_on:date,quantity:1},{onConflict:"habit_id,completed_on"});if(write)throw databaseError(write,"Unable to check in habit");const{data:verified}=await c.from("habit_checkins").select("habit_id,completed_on").eq("habit_id",habit.id).eq("completed_on",date).maybeSingle();return verified?{success:true,record:{name:habit.name,...verified}}:{success:false,error:"The habit check-in could not be verified."};}
async function runAssign(input:unknown):Promise<ToolResult>{const p=assignTask.safeParse(input);if(!p.success)return{success:false,error:"A task and team are required."};const c=supabase();const[{data:task,error:taskError},found]=await Promise.all([c.from("tasks").select("id,title").ilike("title",p.data.task_title).eq("archived",false).maybeSingle(),findTeam(c,p.data.team_name)]);if(taskError)throw databaseError(taskError,"Unable to find task");if(!task)return{success:false,error:`Task \"${p.data.task_title}\" was not found.`};if(!found.team)return{success:false,error:`No matching team. Choose: ${found.names.join(", ")}.`};const{error}=await c.from("tasks").update({team_id:found.team.id}).eq("id",task.id);if(error)throw databaseError(error,"Unable to assign task");const{data:verified}=await c.from("tasks").select("id,title,team_id").eq("id",task.id).eq("team_id",found.team.id).maybeSingle();return verified?{success:true,record:{...verified,team_name:found.team.name}}:{success:false,error:"The task assignment could not be verified."};}
async function runTeam(input:unknown):Promise<ToolResult>{const p=createTeam.safeParse(input);if(!p.success)return{success:false,error:p.error.issues[0]?.message||"Invalid team"};const record=await createTeamRecord(teamSchema.parse({name:p.data.name,description:p.data.description}));const verified=await supabase().from("teams").select("id,name,description").eq("id",record.id).maybeSingle();return verified.data?{success:true,record:verified.data as Record<string,unknown>}:{success:false,error:"The team could not be verified after creation."};}
export function isWriteTool(name:string){return["create_task","checkin_habit","assign_task_to_team","create_team"].includes(name)}
export async function executeAtlasTool(call:ToolCall):Promise<ToolResult>{try{const name=call.function?.name||"",args=JSON.parse(call.function?.arguments||"{}");if(name==="create_task")return runCreateTask(args);if(name==="checkin_habit")return runHabit(args);if(name==="assign_task_to_team")return runAssign(args);if(name==="create_team")return runTeam(args);return{success:false,error:`Unknown Atlas tool: ${name}`}}catch(error){return{success:false,error:error instanceof Error?error.message:"Tool execution failed"}}}
