import { z } from "zod";
import { databaseError, supabase } from "../../db/supabase";

type ToolResult = { success: boolean; error?: string; record?: Record<string, unknown> };
type ToolCall = { id: string; function?: { name?: string; arguments?: string } };

export const atlasTools = [
  { type: "function", function: { name: "create_task", description: "Create a personal or team task. Use this whenever the user asks to add a task.", parameters: { type: "object", properties: { title: { type: "string" }, due_date: { type: "string", description: "YYYY-MM-DD, if supplied" }, priority: { type: "string", enum: ["urgent", "high", "medium", "low"] }, team_name: { type: "string" } }, required: ["title"] } } },
  { type: "function", function: { name: "checkin_habit", description: "Mark a habit complete for today. Use this whenever the user asks to check off or complete a habit.", parameters: { type: "object", properties: { habit_name: { type: "string" } }, required: ["habit_name"] } } },
  { type: "function", function: { name: "assign_task_to_team", description: "Assign an existing task to an existing team.", parameters: { type: "object", properties: { task_title: { type: "string" }, team_name: { type: "string" } }, required: ["task_title", "team_name"] } } },
] as const;

const createTask = z.object({ title: z.string().trim().min(1, "A task title is required").max(200), due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), priority: z.enum(["urgent", "high", "medium", "low"]).default("medium"), team_name: z.string().trim().max(100).optional() });
const checkinHabit = z.object({ habit_name: z.string().trim().min(1, "A habit name is required").max(200) });
const assignTask = z.object({ task_title: z.string().trim().min(1, "A task title is required").max(200), team_name: z.string().trim().min(1, "A team name is required").max(100) });

async function runCreateTask(input: unknown): Promise<ToolResult> {
  const parsed = createTask.safeParse(input); if (!parsed.success) return { success: false, error: parsed.error.issues[0]?.message || "Invalid task" };
  const client = supabase(); let teamId: string | null = null;
  if (parsed.data.team_name) { const { data, error } = await client.from("teams").select("id").ilike("name", parsed.data.team_name).eq("archived", false).maybeSingle(); if (error) throw databaseError(error, "Unable to find team"); if (!data) return { success: false, error: `Team \"${parsed.data.team_name}\" was not found.` }; teamId = String(data.id); }
  const { data, error } = await client.from("tasks").insert({ title: parsed.data.title, due_date: parsed.data.due_date || null, priority: parsed.data.priority, team_id: teamId }).select("id,title,due_date,priority,team_id,status").single(); if (error) throw databaseError(error, "Unable to create task");
  const { data: verified, error: verifyError } = await client.from("tasks").select("id,title,due_date,priority,team_id,status").eq("id", data.id).eq("archived", false).maybeSingle(); if (verifyError) throw databaseError(verifyError, "Unable to verify created task"); if (!verified) return { success: false, error: "The task could not be verified after creation." }; return { success: true, record: verified as Record<string, unknown> };
}
async function runCheckinHabit(input: unknown): Promise<ToolResult> {
  const parsed = checkinHabit.safeParse(input); if (!parsed.success) return { success: false, error: parsed.error.issues[0]?.message || "Invalid habit" }; const client = supabase(); const { data: habit, error } = await client.from("habits").select("id,name").ilike("name", parsed.data.habit_name).eq("archived", false).maybeSingle(); if (error) throw databaseError(error, "Unable to find habit"); if (!habit) return { success: false, error: `Habit \"${parsed.data.habit_name}\" was not found.` }; const completedOn = new Date().toISOString().slice(0, 10); const { error: writeError } = await client.from("habit_checkins").upsert({ habit_id: habit.id, completed_on: completedOn, quantity: 1 }, { onConflict: "habit_id,completed_on" }); if (writeError) throw databaseError(writeError, "Unable to check in habit"); const { data: verified, error: verifyError } = await client.from("habit_checkins").select("habit_id,completed_on,quantity").eq("habit_id", habit.id).eq("completed_on", completedOn).maybeSingle(); if (verifyError) throw databaseError(verifyError, "Unable to verify habit check-in"); if (!verified) return { success: false, error: "The habit check-in could not be verified." }; return { success: true, record: { name: habit.name, ...verified } };
}
async function runAssignTask(input: unknown): Promise<ToolResult> {
  const parsed = assignTask.safeParse(input); if (!parsed.success) return { success: false, error: parsed.error.issues[0]?.message || "Invalid task assignment" }; const client = supabase(); const [{ data: task, error: taskError }, { data: team, error: teamError }] = await Promise.all([client.from("tasks").select("id,title").ilike("title", parsed.data.task_title).eq("archived", false).maybeSingle(), client.from("teams").select("id,name").ilike("name", parsed.data.team_name).eq("archived", false).maybeSingle()]); if (taskError) throw databaseError(taskError, "Unable to find task"); if (teamError) throw databaseError(teamError, "Unable to find team"); if (!task) return { success: false, error: `Task \"${parsed.data.task_title}\" was not found.` }; if (!team) return { success: false, error: `Team \"${parsed.data.team_name}\" was not found.` }; const { error: updateError } = await client.from("tasks").update({ team_id: team.id }).eq("id", task.id); if (updateError) throw databaseError(updateError, "Unable to assign task"); const { data: verified, error: verifyError } = await client.from("tasks").select("id,title,team_id").eq("id", task.id).eq("team_id", team.id).maybeSingle(); if (verifyError) throw databaseError(verifyError, "Unable to verify task assignment"); if (!verified) return { success: false, error: "The task assignment could not be verified." }; return { success: true, record: { ...verified, team_name: team.name } };
}

export function isWriteTool(name: string) { return ["create_task", "checkin_habit", "assign_task_to_team"].includes(name); }
export async function executeAtlasTool(call: ToolCall): Promise<ToolResult> { try { const name = call.function?.name || "", args = JSON.parse(call.function?.arguments || "{}"); if (name === "create_task") return await runCreateTask(args); if (name === "checkin_habit") return await runCheckinHabit(args); if (name === "assign_task_to_team") return await runAssignTask(args); return { success: false, error: `Unknown Atlas tool: ${name}` }; } catch (error) { return { success: false, error: error instanceof Error ? error.message : "Tool execution failed" }; } }
