"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowUpRight, CalendarDays, CheckCircle2, CheckSquare2, ClipboardCheck, FileText, Flag, Heart, Layers3, LayoutDashboard, LoaderCircle, MoreHorizontal, Pencil, Plus, Search, Sparkles, Target, Trash2, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useUiStore } from "../lib/ui-store";
import { ExecutiveDashboard } from "./executive-dashboard";
import { MilestoneFive } from "./milestone-five";
import { MilestoneFour } from "./milestone-four";
import { useFeedback } from "./feedback";

const navigation = [["Dashboard", LayoutDashboard], ["Tasks", ClipboardCheck], ["Projects", Layers3], ["Teams", UsersRound], ["Events", CalendarDays], ["Calendar", CalendarDays], ["Meetings", UsersRound], ["Notes", FileText], ["Knowledge Vault", Sparkles], ["Goals", Flag], ["Habits", Heart], ["Journal", FileText], ["Analytics", ArrowUpRight]] as const;
const colors: Record<string, string> = { cyan: "#22d3ee", blue: "#60a5fa", purple: "#a78bfa", amber: "#fbbf24", rose: "#fb7185", emerald: "#34d399" };

type Team = { id: string; name: string; description: string; members: string; responsibilities: string; currentProjects: string; status: "active" | "planning" | "on_hold"; notes: string; color: string; icon: string; createdAt: string; updatedAt: string };
type Task = { id: string; title: string; description: string; project: string; team: string; priority: "urgent" | "high" | "medium" | "low"; status: "todo" | "in_progress" | "done"; dueDate: string; reminder: string; recurring: string; estimatedTime: string; notes: string; tags: string; createdAt: string; updatedAt: string };
type Project = { id: string; name: string; description: string; team: string; priority: "high" | "medium" | "low"; status: "planning" | "active" | "completed" | "on_hold"; progress: number; startDate: string; deadline: string; milestones: string; risks: string; notes: string; createdAt: string; updatedAt: string };
type Event = { id: string; title: string; startAt: string; team: string; status: string };
type Meeting = { id: string; title: string; scheduledAt: string; team: string; project: string };
type Note = { id: string; title: string; content: string; updatedAt: string };
type Workspace = { kind: "team"; item: Team } | { kind: "task"; item: Task } | { kind: "project"; item: Project };
type Editor = { kind: "team"; item: Team | null } | { kind: "task"; item: Task | null } | { kind: "project"; item: Project | null } | null;

async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "Something went wrong"); } return response.status === 204 ? undefined as T : response.json(); }
const dateLabel = (date?: string) => date ? new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "No date";
const statusLabel = (value: string) => value.replaceAll("_", " ");

export function CouncilOS() {
  const activeSection = useUiStore((state) => state.activeSection);
  const setActiveSection = useUiStore((state) => state.setActiveSection);
  const [editor, setEditor] = useState<Editor>(null);
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [teamSearch, setTeamSearch] = useState("");
  const teamsQuery = useQuery({ queryKey: ["teams"], queryFn: () => request<{ teams: Team[] }>("/api/teams") });
  const tasksQuery = useQuery({ queryKey: ["tasks"], queryFn: () => request<{ tasks: Task[] }>("/api/tasks") });
  const projectsQuery = useQuery({ queryKey: ["projects"], queryFn: () => request<{ projects: Project[] }>("/api/projects") });
  const eventsQuery = useQuery({ queryKey: ["events"], queryFn: () => request<{ events: Event[] }>("/api/events") });
  const meetingsQuery = useQuery({ queryKey: ["meetings"], queryFn: () => request<{ meetings: Meeting[] }>("/api/meetings") });
  const notesQuery = useQuery({ queryKey: ["notes"], queryFn: () => request<{ notes: Note[] }>("/api/notes") });
  const teams = teamsQuery.data?.teams ?? [], tasks = tasksQuery.data?.tasks ?? [], projects = projectsQuery.data?.projects ?? [];
  const visibleTeams = useMemo(() => teams.filter((team) => `${team.name} ${team.description} ${team.members}`.toLowerCase().includes(teamSearch.toLowerCase())), [teams, teamSearch]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setActiveSection("Tasks"); } if (event.key.toLowerCase() === "n" && !event.metaKey && !event.ctrlKey && !(event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)) { if (activeSection === "Teams") setEditor({ kind: "team", item: null }); if (activeSection === "Tasks") setEditor({ kind: "task", item: null }); if (activeSection === "Projects") setEditor({ kind: "project", item: null }); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [activeSection, setActiveSection]);
  const go = (section: string) => { setWorkspace(null); setActiveSection(section); };
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>Council<span>OS</span></span></div><nav>{navigation.map(([label, Icon]) => <button key={label} onClick={() => go(label)} className={`nav-item ${activeSection === label ? "selected" : ""}`}><Icon size={17} /><span>{label}</span>{label === "Tasks" && tasks.filter((task) => task.status !== "done").length ? <small>{tasks.filter((task) => task.status !== "done").length}</small> : null}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><span className="avatar">A</span><span>My workspace</span></button></div></aside>
    <section className="workspace"><header className="topbar"><div className="crumb"><span>Personal command center</span><strong>{activeSection}</strong></div><button className="search-button" onClick={() => go("Tasks")}><Search size={16} /><span>Search workspace</span><kbd>⌘ K</kbd></button></header>
      {activeSection === "Teams" ? <TeamsPage teams={visibleTeams} total={teams.length} loading={teamsQuery.isLoading} error={teamsQuery.error as Error | null} search={teamSearch} onSearch={setTeamSearch} onCreate={() => setEditor({ kind: "team", item: null })} onOpen={(item) => setWorkspace({ kind: "team", item })} /> : null}
      {activeSection === "Tasks" ? <TasksPage tasks={tasks} loading={tasksQuery.isLoading} error={tasksQuery.error as Error | null} onCreate={() => setEditor({ kind: "task", item: null })} onOpen={(item) => setWorkspace({ kind: "task", item })} /> : null}
      {activeSection === "Projects" ? <ProjectsPage projects={projects} loading={projectsQuery.isLoading} error={projectsQuery.error as Error | null} onCreate={() => setEditor({ kind: "project", item: null })} onOpen={(item) => setWorkspace({ kind: "project", item })} /> : null}
      {activeSection === "Events" || activeSection === "Meetings" || activeSection === "Notes" || activeSection === "Calendar" ? <MilestoneFour section={activeSection} teams={teams} projects={projects} tasks={tasks} /> : null}
      {activeSection === "Goals" || activeSection === "Habits" || activeSection === "Knowledge Vault" || activeSection === "Journal" ? <MilestoneFive section={activeSection} /> : null}
      {activeSection === "Dashboard" || activeSection === "Analytics" ? <ExecutiveDashboard onQuickAdd={() => { go("Tasks"); setEditor({ kind: "task", item: null }); }} onSearch={() => go("Tasks")} onNavigate={go} /> : null}
    </section>
    <AnimatePresence>{workspace ? <WorkspaceSheet workspace={workspace} tasks={tasks} projects={projects} events={eventsQuery.data?.events ?? []} meetings={meetingsQuery.data?.meetings ?? []} notes={notesQuery.data?.notes ?? []} onClose={() => setWorkspace(null)} onEdit={() => setEditor({ kind: workspace.kind, item: workspace.item } as Editor)} onNavigate={go} onCreateTask={() => setEditor({ kind: "task", item: null })} onCreateProject={() => setEditor({ kind: "project", item: null })} /> : null}{editor ? <EditorDialog editor={editor} teams={teams} projects={projects} onClose={() => setEditor(null)} /> : null}</AnimatePresence>
  </main>;
}

function PageHeader({ eyebrow, title, detail, action, onAction }: { eyebrow: string; title: string; detail: string; action: string; onAction: () => void }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtle">{detail}</p></div><button className="primary-button" onClick={onAction}><Plus size={17} /> {action}<kbd>N</kbd></button></div>; }
function Loading({ error, loading }: { error: Error | null; loading: boolean }) { return loading ? <div className="loading-state"><LoaderCircle className="spin" size={20} /> Preparing your workspace…</div> : error ? <div className="error-state">{error.message}</div> : null; }
function Empty({ title, detail, action, onAction }: { title: string; detail: string; action: string; onAction: () => void }) { return <div className="large-empty"><div className="empty-state"><span className="empty-icon"><Sparkles size={24} /></span><h3>{title}</h3><p>{detail}</p><button className="secondary-button" onClick={onAction}><Plus size={16} /> {action}</button></div></div>; }

function TeamsPage({ teams, total, loading, error, search, onSearch, onCreate, onOpen }: { teams: Team[]; total: number; loading: boolean; error: Error | null; search: string; onSearch: (value: string) => void; onCreate: () => void; onOpen: (team: Team) => void }) { return <div className="page"><PageHeader eyebrow="Organization" title="Teams" detail="Every group has one calm, connected workspace." action="New team" onAction={onCreate} /><div className="toolbar"><label className="input-wrap"><Search size={16} /><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search teams" /></label><span className="result-count">{total} teams</span></div><Loading loading={loading} error={error} />{!loading && !error && (teams.length ? <div className="team-grid">{teams.map((team) => <TeamCard team={team} key={team.id} onOpen={() => onOpen(team)} />)}</div> : <Empty title="Create your Council structure" detail="Start with the groups you lead. Their work, decisions, and momentum will connect here." action="Create a team" onAction={onCreate} />)}</div>; }
function TeamCard({ team, onOpen }: { team: Team; onOpen: () => void }) { return <motion.article layout className="team-card premium-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="team-card-top"><span className="team-icon" style={{ color: colors[team.color] ?? colors.cyan, backgroundColor: `${colors[team.color] ?? colors.cyan}18` }}><UsersRound size={19} /></span><span className={`status ${team.status}`}>{statusLabel(team.status)}</span></div><button className="card-content-button team-card-body" onClick={onOpen}><h2>{team.name}</h2><p>{team.description || "A dedicated workspace for this team."}</p></button><div className="team-meta"><span><UsersRound size={14} /> {team.members ? `${team.members.split(",").filter(Boolean).length} members` : "Add members"}</span><span><Layers3 size={14} /> {team.currentProjects ? `${team.currentProjects.split(",").filter(Boolean).length} projects` : "No projects"}</span></div><button className="card-footer" onClick={onOpen}>Open workspace <ArrowUpRight size={15} /></button></motion.article>; }

function TasksPage({ tasks, loading, error, onCreate, onOpen }: { tasks: Task[]; loading: boolean; error: Error | null; onCreate: () => void; onOpen: (task: Task) => void }) { const [view, setView] = useState<"all" | "today" | "overdue">("all"); const today = new Date().toISOString().slice(0, 10); const visible = tasks.filter((task) => view === "all" || view === "today" ? task.dueDate === today || view === "all" : Boolean(task.dueDate && task.dueDate < today && task.status !== "done")); return <div className="page"><PageHeader eyebrow="Execution" title="Tasks" detail="The next actions that make progress inevitable." action="New task" onAction={onCreate} /><div className="task-tabs">{(["all", "today", "overdue"] as const).map((tab) => <button className={view === tab ? "active" : ""} onClick={() => setView(tab)} key={tab}>{tab === "all" ? "All tasks" : tab === "today" ? "Today" : "Overdue"}<span>{tab === "all" ? tasks.length : tab === "today" ? tasks.filter((task) => task.dueDate === today).length : tasks.filter((task) => task.dueDate && task.dueDate < today && task.status !== "done").length}</span></button>)}</div><Loading loading={loading} error={error} />{!loading && !error && (visible.length ? <div className="task-list">{visible.map((task) => <TaskRow task={task} key={task.id} onOpen={() => onOpen(task)} />)}</div> : <Empty title={view === "all" ? "Your task list is clear" : `Nothing ${view}`} detail="Capture the next meaningful action whenever it appears." action="Create a task" onAction={onCreate} />)}</div>; }
function TaskRow({ task, onOpen }: { task: Task; onOpen: () => void }) { const client = useQueryClient(); const { toast } = useFeedback(); const complete = useMutation({ mutationFn: () => request(`/api/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ ...task, status: task.status === "done" ? "todo" : "done" }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["tasks"] }); toast(task.status === "done" ? "Task reopened" : "Task completed"); } }); return <article className={`task-row premium-row ${task.status === "done" ? "completed" : ""}`}><button className="complete-toggle" aria-label="Toggle task completion" onClick={() => complete.mutate()}>{task.status === "done" ? <CheckCircle2 size={18} /> : null}</button><button className="task-main task-open-button" onClick={onOpen}><div><h2>{task.title}</h2><span className={`priority ${task.priority}`}>{task.priority}</span></div><p>{[task.project, task.team, task.dueDate ? `Due ${dateLabel(task.dueDate)}` : ""].filter(Boolean).join(" · ") || "No project, team, or date yet"}</p></button><button className="icon-button row-open" aria-label={`Open ${task.title}`} onClick={onOpen}><ArrowUpRight size={16} /></button></article>; }

function ProjectsPage({ projects, loading, error, onCreate, onOpen }: { projects: Project[]; loading: boolean; error: Error | null; onCreate: () => void; onOpen: (project: Project) => void }) { return <div className="page"><PageHeader eyebrow="Strategy" title="Projects" detail="A living workspace for the work that matters most." action="New project" onAction={onCreate} /><Loading loading={loading} error={error} />{!loading && !error && (projects.length ? <div className="team-grid">{projects.map((project) => <ProjectCard project={project} key={project.id} onOpen={() => onOpen(project)} />)}</div> : <Empty title="Make the next initiative visible" detail="Projects become their own workspace for progress, risks, deadlines, and related work." action="Create a project" onAction={onCreate} />)}</div>; }
function ProjectCard({ project, onOpen }: { project: Project; onOpen: () => void }) { return <article className="team-card premium-card"><div className="team-card-top"><span className="team-icon project-icon"><Layers3 size={19} /></span><span className={`status ${project.status === "on_hold" ? "on_hold" : project.status === "active" ? "active" : "planning"}`}>{statusLabel(project.status)}</span></div><button className="card-content-button team-card-body" onClick={onOpen}><h2>{project.name}</h2><p>{project.description || "A focused initiative with room to define its next move."}</p></button><div className="project-progress"><div><span>Momentum</span><strong>{project.progress}%</strong></div><i><b style={{ width: `${project.progress}%` }} /></i></div><div className="team-meta"><span>{project.team || "No team"}</span><span>{project.deadline ? `Due ${dateLabel(project.deadline)}` : "No deadline"}</span></div><button className="card-footer" onClick={onOpen}>Open workspace <ArrowUpRight size={15} /></button></article>; }

function WorkspaceSheet({ workspace, tasks, projects, events, meetings, notes, onClose, onEdit, onNavigate, onCreateTask, onCreateProject }: { workspace: Workspace; tasks: Task[]; projects: Project[]; events: Event[]; meetings: Meeting[]; notes: Note[]; onClose: () => void; onEdit: () => void; onNavigate: (section: string) => void; onCreateTask: () => void; onCreateProject: () => void }) {
  const [tab, setTab] = useState("Overview"); const { toast } = useFeedback(); const client = useQueryClient(); const item = workspace.item as any; const relatedTasks = workspace.kind === "team" ? tasks.filter((task) => task.team === workspace.item.name) : workspace.kind === "project" ? tasks.filter((task) => task.project === workspace.item.name) : [];
  const relatedProjects = workspace.kind === "team" ? projects.filter((project) => project.team === workspace.item.name) : [];
  const relatedEvents = workspace.kind === "team" ? events.filter((event) => event.team === workspace.item.name) : [];
  const relatedMeetings = workspace.kind === "project" ? meetings.filter((meeting) => meeting.project === workspace.item.name) : workspace.kind === "team" ? meetings.filter((meeting) => meeting.team === workspace.item.name) : [];
  const title = workspace.kind === "team" ? item.name : workspace.kind === "task" ? item.title : item.name;
  const remove = useMutation({ mutationFn: () => request(`/api/${workspace.kind === "team" ? "teams" : workspace.kind === "task" ? "tasks" : "projects"}/${item.id}`, { method: "DELETE" }), onSuccess: () => { client.invalidateQueries({ queryKey: [workspace.kind === "team" ? "teams" : workspace.kind === "task" ? "tasks" : "projects"] }); toast(`${workspace.kind === "team" ? "Team" : workspace.kind === "task" ? "Task" : "Project"} deleted`); onClose(); } });
  const tabs = workspace.kind === "team" ? ["Overview", "Members", "Tasks", "Projects", "Events", "Notes", "Activity"] : workspace.kind === "project" ? ["Overview", "Tasks", "Milestones", "Timeline", "Meetings", "Notes", "Activity", "Insights"] : ["Overview", "Timeline", "Notes", "Activity"];
  const overview = workspace.kind === "team" ? <><Stat label="Open tasks" value={relatedTasks.filter((task) => task.status !== "done").length} /><Stat label="Completed tasks" value={relatedTasks.filter((task) => task.status === "done").length} /><Stat label="Projects" value={relatedProjects.length} /><Stat label="Events" value={relatedEvents.length} /></> : workspace.kind === "project" ? <><Stat label="Progress" value={`${item.progress}%`} /><Stat label="Open tasks" value={relatedTasks.filter((task) => task.status !== "done").length} /><Stat label="Meetings" value={relatedMeetings.length} /><Stat label="Deadline" value={item.deadline ? dateLabel(item.deadline) : "—"} /></> : <><Stat label="Priority" value={item.priority} /><Stat label="Status" value={statusLabel(item.status)} /><Stat label="Deadline" value={item.dueDate ? dateLabel(item.dueDate) : "—"} /><Stat label="Project" value={item.project || "—"} /></>;
  const list = (records: { id: string; title?: string; name?: string; description?: string; content?: string; status?: string }[], empty: string) => records.length ? <div className="workspace-list">{records.map((record) => <div className="workspace-list-item" key={record.id}><span><Target size={14} /></span><div><strong>{record.title ?? record.name}</strong><small>{record.description ?? record.content ?? record.status ?? "Open details for context"}</small></div></div>)}</div> : <div className="workspace-empty">{empty}</div>;
  const tabContent = tab === "Overview" ? <><section className="workspace-stats">{overview}</section><section className="workspace-panel"><p className="eyebrow">Executive brief</p><h3>{workspace.kind === "team" ? item.description || "Define what this team owns and how it moves the Council forward." : workspace.kind === "project" ? item.description || "Define the outcome, risks, and next milestone." : item.description || "Add context so this commitment is clear and actionable."}</h3>{workspace.kind === "project" ? <p>{item.risks ? `Risk watch: ${item.risks}` : "No risks recorded yet. Add one before it becomes a surprise."}</p> : null}</section></> : tab === "Tasks" ? list(relatedTasks, "No connected tasks yet. Add the first next action.") : tab === "Projects" ? list(relatedProjects, "No projects connected to this team yet.") : tab === "Events" ? list(relatedEvents, "No events planned for this team yet.") : tab === "Meetings" ? list(relatedMeetings, "No meetings connected yet.") : tab === "Notes" ? list(notes.slice(0, 4), "No notes yet.") : tab === "Members" ? <section className="workspace-panel"><p className="eyebrow">People</p><h3>{workspace.kind === "team" && item.members ? item.members : "Add the people who move this work forward."}</h3></section> : tab === "Milestones" ? <section className="workspace-panel"><p className="eyebrow">Milestones</p><h3>{workspace.kind === "project" && item.milestones ? item.milestones : "Break the work into visible checkpoints."}</h3></section> : <section className="workspace-panel"><p className="eyebrow">Activity</p><h3>Your activity trail will appear here as work is completed and updated.</h3></section>;
  return <motion.div className="workspace-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.aside className="workspace-sheet" initial={{ x: 34, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: 34, opacity: 0 }} onMouseDown={(event) => event.stopPropagation()}><header className="workspace-hero"><button className="back-button" onClick={onClose}><ArrowLeft size={16} /> Back</button><div className="workspace-hero-top"><span className="workspace-icon">{workspace.kind === "team" ? <UsersRound size={22} /> : workspace.kind === "project" ? <Layers3 size={22} /> : <CheckSquare2 size={22} />}</span><div className="hero-actions"><button className="secondary-button" onClick={onEdit}><Pencil size={15} /> Edit</button><button className="icon-button" aria-label="Close workspace" onClick={onClose}><X size={20} /></button></div></div><h1>{title}</h1><p>{workspace.kind === "task" ? statusLabel(item.status) : workspace.kind === "team" ? statusLabel(item.status) : `${statusLabel(item.status)} · ${item.priority} priority`}</p><div className="workspace-actions">{workspace.kind !== "task" ? <button className="primary-button" onClick={workspace.kind === "team" ? onCreateTask : onCreateTask}><Plus size={15} /> Add task</button> : <button className="primary-button" onClick={() => { onNavigate("Tasks"); onClose(); }}><CheckSquare2 size={15} /> View tasks</button>}{workspace.kind === "team" ? <button className="secondary-button" onClick={onCreateProject}><Plus size={15} /> Add project</button> : null}<button className="secondary-button danger-action" onClick={() => window.confirm(`Delete ${title}?`) && remove.mutate()}><Trash2 size={15} /> Delete</button></div></header><nav className="workspace-tabs">{tabs.map((name) => <button key={name} className={tab === name ? "active" : ""} onClick={() => setTab(name)}>{name}</button>)}</nav><div className="workspace-content">{tabContent}</div></motion.aside></motion.div>;
}
function Stat({ label, value }: { label: string; value: string | number }) { return <article><span>{label}</span><strong>{value}</strong></article>; }

function EditorDialog({ editor, teams, projects, onClose }: { editor: Exclude<Editor, null>; teams: Team[]; projects: Project[]; onClose: () => void }) {
  if (editor.kind === "team") return <TeamEditor item={editor.item} onClose={onClose} />;
  if (editor.kind === "task") return <TaskEditor item={editor.item} teams={teams} projects={projects} onClose={onClose} />;
  return <ProjectEditor item={editor.item} teams={teams} onClose={onClose} />;
}
function Dialog({ title, subtitle, error, saving, onClose, onSave, children }: { title: string; subtitle: string; error: Error | null; saving: boolean; onClose: () => void; onSave: () => void; children: React.ReactNode }) { return <motion.div className="dialog-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.div className="dialog" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 16 }} onMouseDown={(event) => event.stopPropagation()}><div className="dialog-header"><div><p className="eyebrow">{subtitle}</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><form onSubmit={(event) => { event.preventDefault(); onSave(); }}><div className="form-body">{children}</div>{error ? <p className="form-error">{error.message}</p> : null}<div className="dialog-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <CheckSquare2 size={16} />} Save changes</button></div></form></motion.div></motion.div>; }
function Input({ label, value, onChange, area, type = "text", options }: { label: string; value: string; onChange: (value: string) => void; area?: boolean; type?: string; options?: { value: string; label: string }[] }) { return <label className="field"><span>{label}</span>{options ? <select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : area ? <textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} />}</label>; }
function TeamEditor({ item, onClose }: { item: Team | null; onClose: () => void }) { const client = useQueryClient(); const { toast } = useFeedback(); const [values, setValues] = useState({ name: item?.name ?? "", description: item?.description ?? "", members: item?.members ?? "", responsibilities: item?.responsibilities ?? "", currentProjects: item?.currentProjects ?? "", status: item?.status ?? "active", notes: item?.notes ?? "", color: item?.color ?? "cyan", icon: item?.icon ?? "layers" }); const set = (key: keyof typeof values) => (value: string) => setValues((current) => ({ ...current, [key]: value })); const save = useMutation({ mutationFn: () => request(item ? `/api/teams/${item.id}` : "/api/teams", { method: item ? "PATCH" : "POST", body: JSON.stringify(values) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["teams"] }); toast(item ? "Team updated" : "Team created"); onClose(); } }); return <Dialog title={item ? `Edit ${item.name}` : "Create a team"} subtitle="Team workspace" error={save.error} saving={save.isPending} onClose={onClose} onSave={() => save.mutate()}><Input label="Team name" value={values.name} onChange={set("name")} /><Input label="Purpose" value={values.description} onChange={set("description")} area /><div className="form-row"><Input label="Status" value={values.status} onChange={set("status")} options={[{ value: "active", label: "Active" }, { value: "planning", label: "Planning" }, { value: "on_hold", label: "On hold" }]} /><Input label="Color" value={values.color} onChange={set("color")} options={Object.keys(colors).map((value) => ({ value, label: value }))} /></div><Input label="Members" value={values.members} onChange={set("members")} /><Input label="Responsibilities" value={values.responsibilities} onChange={set("responsibilities")} area /><Input label="Current projects" value={values.currentProjects} onChange={set("currentProjects")} /><Input label="Notes" value={values.notes} onChange={set("notes")} area /></Dialog>; }
function TaskEditor({ item, teams, projects, onClose }: { item: Task | null; teams: Team[]; projects: Project[]; onClose: () => void }) { const client = useQueryClient(); const { toast } = useFeedback(); const [values, setValues] = useState({ title: item?.title ?? "", description: item?.description ?? "", project: item?.project ?? "", team: item?.team ?? "", priority: item?.priority ?? "medium", status: item?.status ?? "todo", dueDate: item?.dueDate ?? "", reminder: item?.reminder ?? "", recurring: item?.recurring ?? "", estimatedTime: item?.estimatedTime ?? "", notes: item?.notes ?? "", tags: item?.tags ?? "" }); const set = (key: keyof typeof values) => (value: string) => setValues((current) => ({ ...current, [key]: value })); const save = useMutation({ mutationFn: () => request(item ? `/api/tasks/${item.id}` : "/api/tasks", { method: item ? "PATCH" : "POST", body: JSON.stringify(values) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["tasks"] }); toast(item ? "Task updated" : "Task created"); onClose(); } }); return <Dialog title={item ? `Edit ${item.title}` : "Create a task"} subtitle="Task workspace" error={save.error} saving={save.isPending} onClose={onClose} onSave={() => save.mutate()}><Input label="Task" value={values.title} onChange={set("title")} /><Input label="Description" value={values.description} onChange={set("description")} area /><div className="form-row"><Input label="Status" value={values.status} onChange={set("status")} options={[{ value: "todo", label: "To do" }, { value: "in_progress", label: "In progress" }, { value: "done", label: "Done" }]} /><Input label="Priority" value={values.priority} onChange={set("priority")} options={["urgent", "high", "medium", "low"].map((value) => ({ value, label: value }))} /></div><div className="form-row"><Input label="Due date" value={values.dueDate} onChange={set("dueDate")} type="date" /><Input label="Team" value={values.team} onChange={set("team")} options={[{ value: "", label: "No team" }, ...teams.map((team) => ({ value: team.name, label: team.name }))]} /></div><Input label="Project" value={values.project} onChange={set("project")} options={[{ value: "", label: "No project" }, ...projects.map((project) => ({ value: project.name, label: project.name }))]} /><div className="form-row"><Input label="Estimated time" value={values.estimatedTime} onChange={set("estimatedTime")} /><Input label="Recurring" value={values.recurring} onChange={set("recurring")} /></div><Input label="Tags" value={values.tags} onChange={set("tags")} /><Input label="Notes" value={values.notes} onChange={set("notes")} area /></Dialog>; }
function ProjectEditor({ item, teams, onClose }: { item: Project | null; teams: Team[]; onClose: () => void }) { const client = useQueryClient(); const { toast } = useFeedback(); const [values, setValues] = useState({ name: item?.name ?? "", description: item?.description ?? "", team: item?.team ?? "", priority: item?.priority ?? "medium", status: item?.status ?? "planning", progress: String(item?.progress ?? 0), startDate: item?.startDate ?? "", deadline: item?.deadline ?? "", milestones: item?.milestones ?? "", risks: item?.risks ?? "", notes: item?.notes ?? "" }); const set = (key: keyof typeof values) => (value: string) => setValues((current) => ({ ...current, [key]: value })); const save = useMutation({ mutationFn: () => request(item ? `/api/projects/${item.id}` : "/api/projects", { method: item ? "PATCH" : "POST", body: JSON.stringify({ ...values, progress: Number(values.progress) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["projects"] }); toast(item ? "Project updated" : "Project created"); onClose(); } }); return <Dialog title={item ? `Edit ${item.name}` : "Create a project"} subtitle="Project workspace" error={save.error} saving={save.isPending} onClose={onClose} onSave={() => save.mutate()}><Input label="Project name" value={values.name} onChange={set("name")} /><Input label="Outcome" value={values.description} onChange={set("description")} area /><div className="form-row"><Input label="Team" value={values.team} onChange={set("team")} options={[{ value: "", label: "No team" }, ...teams.map((team) => ({ value: team.name, label: team.name }))]} /><Input label="Status" value={values.status} onChange={set("status")} options={["planning", "active", "completed", "on_hold"].map((value) => ({ value, label: statusLabel(value) }))} /></div><div className="form-row"><Input label="Priority" value={values.priority} onChange={set("priority")} options={["high", "medium", "low"].map((value) => ({ value, label: value }))} /><Input label="Progress" value={values.progress} onChange={set("progress")} type="number" /></div><div className="form-row"><Input label="Start date" value={values.startDate} onChange={set("startDate")} type="date" /><Input label="Deadline" value={values.deadline} onChange={set("deadline")} type="date" /></div><Input label="Milestones" value={values.milestones} onChange={set("milestones")} area /><Input label="Risks" value={values.risks} onChange={set("risks")} area /><Input label="Notes" value={values.notes} onChange={set("notes")} area /></Dialog>; }
