"use client";

import { useQuery } from "@tanstack/react-query";
import { Bell, CalendarDays, CheckCircle2, CircleCheck, Clock3, FileText, Layers3, ListTodo, LoaderCircle, Plus, Search, Sparkles, Target, TrendingUp } from "lucide-react";

type Task = { id: string; title: string; dueDate: string; status: string; priority: string; project: string; team: string };
type Event = { id: string; title: string; startAt: string };
type Meeting = { id: string; title: string; scheduledAt: string };
type Project = { id: string; name: string; progress: number; deadline: string };
type Habit = { id: string; name: string; completedToday: boolean };
type Note = { id: string; title: string; content: string };
async function request<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error("Unable to load your daily briefing"); return response.json(); }
const today = () => new Date().toISOString().slice(0, 10);
const greeting = () => new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 18 ? "Good afternoon" : "Good evening";
const priorityColor = (priority: string) => priority === "urgent" || priority === "high" ? "red" : priority === "medium" ? "orange" : "blue";

export function ExecutiveDashboard({ onQuickAdd, onSearch, onNavigate }: { onQuickAdd: () => void; onSearch: () => void; onNavigate: (section: string) => void }) {
  const tasksQuery = useQuery({ queryKey: ["tasks"], queryFn: () => request<{ tasks: Task[] }>("/api/tasks") });
  const projectsQuery = useQuery({ queryKey: ["projects"], queryFn: () => request<{ projects: Project[] }>("/api/projects") });
  const eventsQuery = useQuery({ queryKey: ["events"], queryFn: () => request<{ events: Event[] }>("/api/events") });
  const meetingsQuery = useQuery({ queryKey: ["meetings"], queryFn: () => request<{ meetings: Meeting[] }>("/api/meetings") });
  const habitsQuery = useQuery({ queryKey: ["habits"], queryFn: () => request<{ habits: Habit[] }>("/api/habits") });
  const notesQuery = useQuery({ queryKey: ["notes"], queryFn: () => request<{ notes: Note[] }>("/api/notes") });
  if ([tasksQuery, projectsQuery, eventsQuery, meetingsQuery, habitsQuery, notesQuery].some((query) => query.isLoading)) return <div className="page loading-state"><LoaderCircle className="spin" size={20} /> Preparing your daily command center…</div>;
  const tasks = tasksQuery.data?.tasks ?? [], projects = projectsQuery.data?.projects ?? [], events = eventsQuery.data?.events ?? [], meetings = meetingsQuery.data?.meetings ?? [], habits = habitsQuery.data?.habits ?? [], notes = notesQuery.data?.notes ?? [];
  const date = today(); const dueToday = tasks.filter((task) => task.dueDate === date && task.status !== "done"); const overdue = tasks.filter((task) => task.dueDate && task.dueDate < date && task.status !== "done"); const completed = tasks.filter((task) => task.status === "done"); const upcoming = [...meetings.map((meeting) => ({ id: meeting.id, title: meeting.title, when: meeting.scheduledAt, type: "Meeting" })), ...events.map((event) => ({ id: event.id, title: event.title, when: event.startAt, type: "Event" }))].filter((item) => new Date(item.when) >= new Date()).sort((a, b) => a.when.localeCompare(b.when)).slice(0, 4); const habitDone = habits.filter((habit) => habit.completedToday).length;
  const plan = [...overdue, ...dueToday, ...tasks.filter((task) => task.status !== "done" && task.dueDate > date)].slice(0, 5); const days = calendarDays();
  return <div className="page daily-home">
    <div className="daily-toolbar"><button className="daily-search" onClick={onSearch}><Search size={18} /><span>Search tasks, notes, projects…</span><kbd>⌘ K</kbd></button><div><button className="round-top-button" aria-label="Notifications"><Bell size={18} /></button><button className="round-top-button" aria-label="Productivity"><TrendingUp size={18} /></button></div></div>
    <div className="daily-layout"><main className="daily-main"><section className="daily-greeting"><div><h1>{greeting()}, Aryan <span>👋</span></h1><p>Focus. Plan. Execute. Repeat.</p></div><button className="quick-add" onClick={onQuickAdd}><Plus size={18} /> Quick Add</button></section>
      <section className="metric-grid"><Metric icon={<CircleCheck size={21} />} tone="blue" value={dueToday.length} label="Tasks Today" progress={Math.min(100, dueToday.length * 12)} /><Metric icon={<Clock3 size={21} />} tone="orange" value={overdue.length} label="Due Soon" progress={Math.min(100, overdue.length * 18)} /><Metric icon={<CheckCircle2 size={21} />} tone="green" value={completed.length} label="Completed" progress={tasks.length ? completed.length / tasks.length * 100 : 0} /><Metric icon={<Sparkles size={21} />} tone="purple" value={habitDone} label="Habit Streak" progress={habits.length ? habitDone / habits.length * 100 : 0} /></section>
      <section className="daily-panel plan-panel"><div className="daily-panel-heading"><div><ListTodo size={18} /><h2>Today’s Plan</h2></div><button onClick={() => onNavigate("Tasks")}>View all</button></div>{plan.length ? <div className="plan-list">{plan.map((task) => <button key={task.id} className="plan-row" onClick={() => onNavigate("Tasks")}><span className="plan-check" /><strong>{task.title}</strong><span className={`priority-dot ${priorityColor(task.priority)}`} /><small>{task.priority}</small><time>{task.dueDate ? new Date(`${task.dueDate}T12:00:00`).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "Anytime"}</time></button>)}</div> : <div className="plan-empty">Your plan is clear. Add one meaningful next action.</div>}<button className="plan-add" onClick={onQuickAdd}><Plus size={18} /> Add new task</button></section>
      <section className="daily-panel projects-strip"><div className="daily-panel-heading"><h2>Projects</h2><button onClick={() => onNavigate("Projects")}>View all</button></div><div className="project-pills">{projects.length ? projects.slice(0, 4).map((project, index) => <button onClick={() => onNavigate("Projects")} key={project.id}><span className={`project-pill-icon p${index % 4}`}><Layers3 size={17} /></span><span><strong>{project.name}</strong><small>{project.progress}% complete</small></span></button>) : <button onClick={() => onNavigate("Projects")}><span className="project-pill-icon p0"><Layers3 size={17} /></span><span><strong>Start a project</strong><small>Give your biggest work a home</small></span></button>}</div></section>
      <div className="daily-note"><Sparkles size={16} /> You’re doing great. Keep the momentum going.</div>
    </main><aside className="daily-side"><section className="calendar-card"><div className="calendar-card-heading"><h2>{new Date().toLocaleDateString(undefined, { month: "long", year: "numeric" })}</h2><CalendarDays size={18} /></div><div className="calendar-weekdays">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-days">{days.map((day, index) => <span className={day.current ? "current-day" : day.muted ? "muted-day" : ""} key={index}>{day.value}</span>)}</div></section><section className="daily-panel upcoming-card"><div className="daily-panel-heading"><h2>Upcoming</h2><button onClick={() => onNavigate("Calendar")}>View all</button></div>{upcoming.length ? <div className="upcoming-list">{upcoming.map((item, index) => <button onClick={() => onNavigate(item.type === "Meeting" ? "Meetings" : "Events")} key={`${item.type}-${item.id}`}><span className={`upcoming-dot d${index % 4}`} /><span><strong>{item.title}</strong><small>{item.type} · {new Date(item.when).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</small></span></button>)}</div> : <div className="plan-empty">Nothing scheduled. A calm week ahead.</div>}</section><section className="quote-card"><span>“</span><p>Discipline is choosing what you want most over what you want now.</p><i /></section>{notes[0] ? <button className="recent-note" onClick={() => onNavigate("Notes")}><FileText size={16} /><span><strong>Recent note</strong><small>{notes[0].title || notes[0].content}</small></span></button> : null}</aside></div>
  </div>;
}
function Metric({ icon, tone, value, label, progress }: { icon: React.ReactNode; tone: string; value: number; label: string; progress: number }) { return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><strong>{value}</strong><small>{label}</small><i><b style={{ width: `${progress}%` }} /></i></article>; }
function calendarDays() { const now = new Date(); const year = now.getFullYear(); const month = now.getMonth(); const first = new Date(year, month, 1); const start = (first.getDay() + 6) % 7; const daysInMonth = new Date(year, month + 1, 0).getDate(); const previous = new Date(year, month, 0).getDate(); return Array.from({ length: 35 }, (_, index) => { const offset = index - start + 1; return offset < 1 ? { value: previous + offset, muted: true, current: false } : offset > daysInMonth ? { value: offset - daysInMonth, muted: true, current: false } : { value: offset, muted: false, current: offset === now.getDate() }; }); }
