"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, CheckSquare2, FileText, LoaderCircle, MapPin, Pencil, Pin, Plus, Trash2, UsersRound, X } from "lucide-react";
import { useMemo, useState } from "react";

type Team = { id: string; name: string };
type Project = { id: string; name: string; deadline: string };
type Task = { id: string; title: string; dueDate: string; status: string };
type Event = { id: string; title: string; description: string; startAt: string; endAt: string; venue: string; budget: number | ""; status: "draft" | "planned" | "completed" | "cancelled"; preparationChecklist: string; notes: string; team: string; createdAt: string; updatedAt: string };
type Meeting = { id: string; title: string; scheduledAt: string; durationMinutes: number; locationOrLink: string; agenda: string; discussion: string; decisions: string; actionItems: string; followUps: string; notes: string; team: string; project: string; createdAt: string; updatedAt: string };
type Note = { id: string; title: string; content: string; category: string; tags: string; pinned: boolean; createdAt: string; updatedAt: string };
type Section = "Events" | "Meetings" | "Notes" | "Calendar";

async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "Something went wrong"); } return response.status === 204 ? undefined as T : response.json(); }
const localInput = (value: string) => value ? new Date(value).toISOString().slice(0, 16) : "";
const displayDate = (value: string, includeTime = true) => value ? new Date(value).toLocaleString(undefined, includeTime ? { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" } : { month: "short", day: "numeric", year: "numeric" }) : "Unscheduled";
const dateKey = (value: string) => value ? new Date(value).toLocaleDateString(undefined, { year: "numeric", month: "2-digit", day: "2-digit" }) : "";

export function MilestoneFour({ section, teams, projects, tasks }: { section: Section; teams: Team[]; projects: Project[]; tasks: Task[] }) {
  const [eventEditor, setEventEditor] = useState<Event | "new" | null>(null); const [meetingEditor, setMeetingEditor] = useState<Meeting | "new" | null>(null); const [noteEditor, setNoteEditor] = useState<Note | "new" | null>(null);
  const eventsQuery = useQuery({ queryKey: ["events"], queryFn: () => request<{ events: Event[] }>("/api/events") });
  const meetingsQuery = useQuery({ queryKey: ["meetings"], queryFn: () => request<{ meetings: Meeting[] }>("/api/meetings") });
  const notesQuery = useQuery({ queryKey: ["notes"], queryFn: () => request<{ notes: Note[] }>("/api/notes") });
  const events = eventsQuery.data?.events ?? [], meetings = meetingsQuery.data?.meetings ?? [], notes = notesQuery.data?.notes ?? [];
  return <><div className="page">{section === "Events" ? <EventsPage events={events} loading={eventsQuery.isLoading} error={eventsQuery.error} onCreate={() => setEventEditor("new")} onEdit={setEventEditor} /> : section === "Meetings" ? <MeetingsPage meetings={meetings} loading={meetingsQuery.isLoading} error={meetingsQuery.error} onCreate={() => setMeetingEditor("new")} onEdit={setMeetingEditor} /> : section === "Notes" ? <NotesPage notes={notes} loading={notesQuery.isLoading} error={notesQuery.error} onCreate={() => setNoteEditor("new")} onEdit={setNoteEditor} /> : <CalendarPage events={events} meetings={meetings} tasks={tasks} projects={projects} onEvent={setEventEditor} onMeeting={setMeetingEditor} />}</div>{eventEditor ? <EventEditor event={eventEditor === "new" ? null : eventEditor} teams={teams} onClose={() => setEventEditor(null)} /> : null}{meetingEditor ? <MeetingEditor meeting={meetingEditor === "new" ? null : meetingEditor} teams={teams} projects={projects} onClose={() => setMeetingEditor(null)} /> : null}{noteEditor ? <NoteEditor note={noteEditor === "new" ? null : noteEditor} onClose={() => setNoteEditor(null)} /> : null}</>;
}

function PageHeading({ eyebrow, title, detail, action, onAction }: { eyebrow: string; title: string; detail: string; action: string; onAction: () => void }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtle">{detail}</p></div><button className="primary-button" onClick={onAction}><Plus size={17} /> {action}</button></div>; }
function LoadingOrError({ loading, error }: { loading: boolean; error: Error | null }) { return loading ? <div className="loading-state"><LoaderCircle className="spin" size={20} /> Loading your workspace…</div> : error ? <div className="error-state">{error.message}</div> : null; }

function EventsPage({ events, loading, error, onCreate, onEdit }: { events: Event[]; loading: boolean; error: Error | null; onCreate: () => void; onEdit: (event: Event) => void }) { const [filter, setFilter] = useState("all"); const visible = events.filter((event) => filter === "all" || event.status === filter); return <><PageHeading eyebrow="Planning & delivery" title="Events" detail="Plan the moments that bring your Council’s work to life." action="New event" onAction={onCreate} /><div className="task-tabs">{["all", "draft", "planned", "completed", "cancelled"].map((status) => <button className={filter === status ? "active" : ""} key={status} onClick={() => setFilter(status)}>{status === "all" ? "All events" : status}<span>{status === "all" ? events.length : events.filter((event) => event.status === status).length}</span></button>)}</div><LoadingOrError loading={loading} error={error} />{!loading && !error && (visible.length ? <div className="m4-card-grid">{visible.map((event) => <EventCard event={event} onEdit={() => onEdit(event)} key={event.id} />)}</div> : <Empty title="No events yet" detail="Plan an event with its timeline, venue, preparation checklist, and budget." action="Create your first event" onAction={onCreate} />)}</>; }
function EventCard({ event, onEdit }: { event: Event; onEdit: () => void }) { const client = useQueryClient(); const remove = useMutation({ mutationFn: () => request(`/api/events/${event.id}`, { method: "DELETE" }), onSuccess: () => client.invalidateQueries({ queryKey: ["events"] }) }); return <article className="m4-card"><div className="m4-card-head"><span className={`m4-status ${event.status}`}>{event.status.replace("_", " ")}</span><div className="row-actions"><button aria-label={`Edit ${event.title}`} onClick={onEdit}><Pencil size={15} /></button><button aria-label={`Delete ${event.title}`} onClick={() => window.confirm(`Delete ${event.title}?`) && remove.mutate()}><Trash2 size={15} /></button></div></div><h2>{event.title}</h2><p>{event.description || "No event brief yet."}</p><div className="m4-meta"><span><CalendarClock size={14} /> {displayDate(event.startAt)}</span>{event.venue ? <span><MapPin size={14} /> {event.venue}</span> : null}{event.team ? <span><UsersRound size={14} /> {event.team}</span> : null}</div><button className="card-footer" onClick={onEdit}>Open event <CalendarClock size={15} /></button></article>; }

function MeetingsPage({ meetings, loading, error, onCreate, onEdit }: { meetings: Meeting[]; loading: boolean; error: Error | null; onCreate: () => void; onEdit: (meeting: Meeting) => void }) { const [view, setView] = useState<"upcoming" | "past">("upcoming"); const now = new Date(); const visible = meetings.filter((meeting) => view === "upcoming" ? new Date(meeting.scheduledAt) >= now : new Date(meeting.scheduledAt) < now); return <><PageHeading eyebrow="Leadership cadence" title="Meetings" detail="Prepare an agenda, capture decisions, and make every follow-up explicit." action="New meeting" onAction={onCreate} /><div className="task-tabs">{(["upcoming", "past"] as const).map((tab) => <button key={tab} className={view === tab ? "active" : ""} onClick={() => setView(tab)}>{tab === "upcoming" ? "Upcoming" : "Past meetings"}<span>{meetings.filter((meeting) => tab === "upcoming" ? new Date(meeting.scheduledAt) >= now : new Date(meeting.scheduledAt) < now).length}</span></button>)}</div><LoadingOrError loading={loading} error={error} />{!loading && !error && (visible.length ? <div className="m4-list">{visible.map((meeting) => <MeetingRow meeting={meeting} onEdit={() => onEdit(meeting)} key={meeting.id} />)}</div> : <Empty title={view === "upcoming" ? "No upcoming meetings" : "No past meetings"} detail="Create a meeting to keep the agenda, decisions, and action items together." action="Schedule a meeting" onAction={onCreate} />)}</>; }
function MeetingRow({ meeting, onEdit }: { meeting: Meeting; onEdit: () => void }) { const client = useQueryClient(); const remove = useMutation({ mutationFn: () => request(`/api/meetings/${meeting.id}`, { method: "DELETE" }), onSuccess: () => client.invalidateQueries({ queryKey: ["meetings"] }) }); return <article className="m4-row"><span className="m4-row-icon"><UsersRound size={18} /></span><div className="m4-row-main" onClick={onEdit}><h2>{meeting.title}</h2><p>{[displayDate(meeting.scheduledAt), `${meeting.durationMinutes} min`, meeting.team, meeting.project].filter(Boolean).join(" · ")}</p>{meeting.decisions ? <small>Decision notes captured</small> : null}</div><div className="row-actions"><button aria-label={`Edit ${meeting.title}`} onClick={onEdit}><Pencil size={15} /></button><button aria-label={`Delete ${meeting.title}`} onClick={() => window.confirm(`Delete ${meeting.title}?`) && remove.mutate()}><Trash2 size={15} /></button></div></article>; }

function NotesPage({ notes, loading, error, onCreate, onEdit }: { notes: Note[]; loading: boolean; error: Error | null; onCreate: () => void; onEdit: (note: Note) => void }) { const [search, setSearch] = useState(""); const [category, setCategory] = useState("all"); const categories = Array.from(new Set(notes.map((note) => note.category))).sort(); const visible = notes.filter((note) => (category === "all" || note.category === category) && `${note.title} ${note.content} ${note.tags}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeading eyebrow="Reference & thinking" title="Notes" detail="A quiet space for observations, decisions, and ideas worth retaining." action="New note" onAction={onCreate} /><div className="toolbar"><label className="input-wrap"><FileText size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search notes" /></label><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option>{categories.map((value) => <option value={value} key={value}>{value}</option>)}</select><span className="result-count">{visible.length} {visible.length === 1 ? "note" : "notes"}</span></div><LoadingOrError loading={loading} error={error} />{!loading && !error && (visible.length ? <div className="m4-note-grid">{visible.map((note) => <NoteCard note={note} onEdit={() => onEdit(note)} key={note.id} />)}</div> : <Empty title={search || category !== "all" ? "No matching notes" : "Your notes will collect here"} detail="Capture a thought now; it will be available when the context returns." action={search || category !== "all" ? undefined : "Write your first note"} onAction={onCreate} />)}</>; }
function NoteCard({ note, onEdit }: { note: Note; onEdit: () => void }) { const client = useQueryClient(); const remove = useMutation({ mutationFn: () => request(`/api/notes/${note.id}`, { method: "DELETE" }), onSuccess: () => client.invalidateQueries({ queryKey: ["notes"] }) }); return <article className={`m4-note ${note.pinned ? "pinned" : ""}`}><div className="m4-card-head"><span className="m4-category">{note.category}</span><div className="row-actions">{note.pinned ? <Pin size={14} /> : null}<button aria-label={`Edit ${note.title}`} onClick={onEdit}><Pencil size={15} /></button><button aria-label={`Delete ${note.title}`} onClick={() => window.confirm(`Delete ${note.title}?`) && remove.mutate()}><Trash2 size={15} /></button></div></div><h2 onClick={onEdit}>{note.title}</h2><p onClick={onEdit}>{note.content || "Empty note"}</p><footer>{note.tags || "No tags"}<span>{displayDate(note.updatedAt, false)}</span></footer></article>; }

function CalendarPage({ events, meetings, tasks, projects, onEvent, onMeeting }: { events: Event[]; meetings: Meeting[]; tasks: Task[]; projects: Project[]; onEvent: (event: Event) => void; onMeeting: (meeting: Meeting) => void }) { const [mode, setMode] = useState<"agenda" | "month">("agenda"); const items = useMemo(() => [...events.map((event) => ({ id: event.id, title: event.title, when: event.startAt, kind: "event" as const, open: () => onEvent(event) })), ...meetings.map((meeting) => ({ id: meeting.id, title: meeting.title, when: meeting.scheduledAt, kind: "meeting" as const, open: () => onMeeting(meeting) })), ...tasks.filter((task) => task.dueDate && task.status !== "done").map((task) => ({ id: task.id, title: task.title, when: `${task.dueDate}T12:00:00`, kind: "task" as const, open: undefined })), ...projects.filter((project) => project.deadline).map((project) => ({ id: project.id, title: project.name, when: `${project.deadline}T12:00:00`, kind: "deadline" as const, open: undefined }))].sort((a, b) => a.when.localeCompare(b.when)), [events, meetings, tasks, projects, onEvent, onMeeting]); const days = Array.from({ length: 28 }, (_, index) => { const date = new Date(); date.setDate(1 + index); return date; }); return <><div className="page-heading"><div><p className="eyebrow">One timeline</p><h1>Calendar</h1><p className="subtle">Events, meetings, task dates, and project deadlines in one place.</p></div><div className="calendar-toggle"><button className={mode === "agenda" ? "active" : ""} onClick={() => setMode("agenda")}>Agenda</button><button className={mode === "month" ? "active" : ""} onClick={() => setMode("month")}>Month</button></div></div>{mode === "agenda" ? <div className="calendar-agenda">{items.length ? items.map((item) => <button className={`calendar-item ${item.kind}`} key={`${item.kind}-${item.id}`} onClick={item.open}><time>{displayDate(item.when)}</time><span>{item.kind === "deadline" ? "Project deadline" : item.kind === "task" ? "Task due" : item.kind}</span><strong>{item.title}</strong></button>) : <Empty title="Your calendar is clear" detail="Events, meetings, tasks with due dates, and project deadlines will appear here." />}</div> : <div className="month-grid">{days.map((day) => { const dayItems = items.filter((item) => dateKey(item.when) === dateKey(day.toISOString())); return <div className="month-day" key={day.toISOString()}><strong>{day.getDate()}</strong>{dayItems.slice(0, 3).map((item) => <button key={`${item.kind}-${item.id}`} className={item.kind} onClick={item.open}>{item.title}</button>)}</div>; })}</div>}</>; }

function Empty({ title, detail, action, onAction }: { title: string; detail: string; action?: string; onAction?: () => void }) { return <div className="large-empty"><div className="empty-state"><span className="empty-icon"><FileText size={24} /></span><h3>{title}</h3><p>{detail}</p>{action ? <button className="secondary-button" onClick={onAction}><Plus size={16} /> {action}</button> : null}</div></div>; }

function EventEditor({ event, teams, onClose }: { event: Event | null; teams: Team[]; onClose: () => void }) { const client = useQueryClient(); const [values, setValues] = useState({ title: event?.title ?? "", description: event?.description ?? "", startAt: localInput(event?.startAt ?? ""), endAt: localInput(event?.endAt ?? ""), venue: event?.venue ?? "", budget: event?.budget === "" || event?.budget === undefined ? "" : String(event.budget), status: event?.status ?? "planned", preparationChecklist: event?.preparationChecklist ?? "", notes: event?.notes ?? "", team: event?.team ?? "" }); const save = useMutation({ mutationFn: () => request(event ? `/api/events/${event.id}` : "/api/events", { method: event ? "PATCH" : "POST", body: JSON.stringify({ ...values, startAt: new Date(values.startAt).toISOString(), endAt: values.endAt ? new Date(values.endAt).toISOString() : "", budget: values.budget === "" ? "" : Number(values.budget) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["events"] }); onClose(); } }); return <Editor title={event ? "Edit event" : "Plan an event"} error={save.error} saving={save.isPending} onClose={onClose} onSubmit={() => save.mutate()}>{({ field }) => <><Field label="Event title" field={field("title")} autoFocus /><Field label="Event brief" field={field("description")} area /><div className="form-row"><Field label="Start" field={field("startAt")} type="datetime-local" /><Field label="End" field={field("endAt")} type="datetime-local" /></div><div className="form-row"><Field label="Venue" field={field("venue")} /><Field label="Budget" field={field("budget")} type="number" /></div><div className="form-row"><SelectField label="Status" field={field("status")} options={["draft", "planned", "completed", "cancelled"]} /><SelectField label="Team" field={field("team")} options={["", ...teams.map((team) => team.name)]} emptyLabel="No team" /></div><Field label="Preparation checklist" field={field("preparationChecklist")} area /><Field label="Notes" field={field("notes")} area /></>}</Editor>; function field(key: keyof typeof values) { return { value: values[key], onChange: (value: string) => setValues((current) => ({ ...current, [key]: value })) }; } }
function MeetingEditor({ meeting, teams, projects, onClose }: { meeting: Meeting | null; teams: Team[]; projects: Project[]; onClose: () => void }) { const client = useQueryClient(); const [values, setValues] = useState({ title: meeting?.title ?? "", scheduledAt: localInput(meeting?.scheduledAt ?? ""), durationMinutes: String(meeting?.durationMinutes ?? 60), locationOrLink: meeting?.locationOrLink ?? "", team: meeting?.team ?? "", project: meeting?.project ?? "", agenda: meeting?.agenda ?? "", discussion: meeting?.discussion ?? "", decisions: meeting?.decisions ?? "", actionItems: meeting?.actionItems ?? "", followUps: meeting?.followUps ?? "", notes: meeting?.notes ?? "" }); const save = useMutation({ mutationFn: () => request(meeting ? `/api/meetings/${meeting.id}` : "/api/meetings", { method: meeting ? "PATCH" : "POST", body: JSON.stringify({ ...values, scheduledAt: new Date(values.scheduledAt).toISOString(), durationMinutes: Number(values.durationMinutes) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["meetings"] }); onClose(); } }); return <Editor title={meeting ? "Edit meeting" : "Schedule a meeting"} error={save.error} saving={save.isPending} onClose={onClose} onSubmit={() => save.mutate()}>{({ field }) => <><Field label="Meeting title" field={field("title")} autoFocus /><div className="form-row"><Field label="When" field={field("scheduledAt")} type="datetime-local" /><Field label="Minutes" field={field("durationMinutes")} type="number" /></div><Field label="Location or video link" field={field("locationOrLink")} /><div className="form-row"><SelectField label="Team" field={field("team")} options={["", ...teams.map((team) => team.name)]} emptyLabel="No team" /><SelectField label="Project" field={field("project")} options={["", ...projects.map((project) => project.name)]} emptyLabel="No project" /></div><Field label="Agenda" field={field("agenda")} area /><Field label="Discussion notes" field={field("discussion")} area /><Field label="Decisions" field={field("decisions")} area /><Field label="Action items" field={field("actionItems")} area /><Field label="Follow-ups" field={field("followUps")} area /><Field label="Additional notes" field={field("notes")} area /></>}</Editor>; function field(key: keyof typeof values) { return { value: values[key], onChange: (value: string) => setValues((current) => ({ ...current, [key]: value })) }; } }
function NoteEditor({ note, onClose }: { note: Note | null; onClose: () => void }) { const client = useQueryClient(); const [values, setValues] = useState({ title: note?.title ?? "", content: note?.content ?? "", category: note?.category ?? "general", tags: note?.tags ?? "", pinned: note?.pinned ?? false }); const save = useMutation({ mutationFn: () => request(note ? `/api/notes/${note.id}` : "/api/notes", { method: note ? "PATCH" : "POST", body: JSON.stringify(values) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["notes"] }); onClose(); } }); return <Editor title={note ? "Edit note" : "Write a note"} error={save.error} saving={save.isPending} onClose={onClose} onSubmit={() => save.mutate()}>{({ field }) => <><Field label="Title" field={field("title")} autoFocus /><Field label="Note" field={field("content")} area /><div className="form-row"><Field label="Category" field={field("category")} /><Field label="Tags" field={field("tags")} /></div><label className="m4-check"><input type="checkbox" checked={values.pinned} onChange={(event) => setValues((current) => ({ ...current, pinned: event.target.checked }))} /> Pin this note</label></>}</Editor>; function field(key: "title" | "content" | "category" | "tags") { return { value: values[key], onChange: (value: string) => setValues((current) => ({ ...current, [key]: value })) }; } }
function Editor({ title, error, saving, onClose, onSubmit, children }: { title: string; error: Error | null; saving: boolean; onClose: () => void; onSubmit: () => void; children: (helpers: { field: (name: never) => never }) => React.ReactNode }) { return <div className="dialog-backdrop" onMouseDown={onClose}><div className="dialog m4-dialog" onMouseDown={(event) => event.stopPropagation()}><div className="dialog-header"><div><p className="eyebrow">Milestone 4</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><div className="form-body">{children({ field: () => undefined as never })}</div>{error ? <p className="form-error">{error.message}</p> : null}<div className="dialog-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <CheckSquare2 size={16} />} Save</button></div></form></div></div>; }
function Field({ label, field, area, type = "text", autoFocus = false }: { label: string; field: { value: string; onChange: (value: string) => void }; area?: boolean; type?: string; autoFocus?: boolean }) { return <label className="field"><span>{label}</span>{area ? <textarea rows={3} value={field.value} onChange={(event) => field.onChange(event.target.value)} /> : <input autoFocus={autoFocus} type={type} value={field.value} onChange={(event) => field.onChange(event.target.value)} />}</label>; }
function SelectField({ label, field, options, emptyLabel }: { label: string; field: { value: string; onChange: (value: string) => void }; options: string[]; emptyLabel?: string }) { return <label className="field"><span>{label}</span><select value={field.value} onChange={(event) => field.onChange(event.target.value)}>{options.map((option) => <option key={option || "empty"} value={option}>{option || emptyLabel || "None"}</option>)}</select></label>; }
