"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Clock3, FileText, Heart, LoaderCircle, Pencil, Plus, Target, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { EntityDetailsDialog } from "./entity-details-dialog";
import { useFeedback } from "./feedback";
import { useUiStore } from "../lib/ui-store";

type Section = "Goals" | "Habits" | "Knowledge Vault" | "Journal";
type RecordItem = Record<string, unknown> & { id: string; title?: string; name?: string; content?: string; description?: string; completedToday?: boolean; progress?: number; status?: string; category?: string; mood?: string; tags?: string };
const config = { Goals: { path: "goals", label: "goal", icon: Target, detail: "Keep your long-term intentions visible, measurable, and moving." }, Habits: { path: "habits", label: "habit", icon: Heart, detail: "Make the practices that compound feel simple every day." }, "Knowledge Vault": { path: "knowledge", label: "entry", icon: FileText, detail: "Collect the ideas and references worth returning to." }, Journal: { path: "journal", label: "entry", icon: FileText, detail: "A private place to retain context and reflect." } } as const;
async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "Something went wrong"); } return response.status === 204 ? undefined as T : response.json(); }

export function MilestoneFive({ section }: { section: Section }) {
  const [editing, setEditing] = useState<RecordItem | "new" | null>(null); const [viewing, setViewing] = useState<RecordItem | null>(null); const itemConfig = config[section]; const Icon = itemConfig.icon;
  const createIntent = useUiStore((state) => state.createIntent); const clearCreateIntent = useUiStore((state) => state.clearCreateIntent);
  useEffect(() => { if (createIntent === section) { setEditing("new"); clearCreateIntent(); } }, [createIntent, section, clearCreateIntent]);
  const query = useQuery({ queryKey: [itemConfig.path], queryFn: () => request<{ goals?: RecordItem[]; habits?: RecordItem[]; entries?: RecordItem[] }>(`/api/${itemConfig.path}`) });
  const items = query.data?.goals ?? query.data?.habits ?? query.data?.entries ?? [];
  return <><div className="page"><div className="page-heading"><div><p className="eyebrow">Personal operating system</p><h1>{section}</h1><p className="subtle">{itemConfig.detail}</p></div><button className="primary-button" onClick={() => setEditing("new")}><Plus size={17} /> New {itemConfig.label}</button></div>{query.isLoading ? <div className="loading-state"><LoaderCircle className="spin" size={20} /> Loading your workspace…</div> : query.error ? <div className="error-state">{query.error.message}</div> : items.length ? <div className={section === "Habits" ? "task-list" : "m4-card-grid"}>{items.map((item) => <Card key={item.id} item={item} section={section} onView={() => setViewing(item)} onEdit={() => setEditing(item)} />)}</div> : <div className="large-empty"><div className="empty-state"><span className="empty-icon"><Icon size={24} /></span><h3>No {section.toLowerCase()} yet</h3><p>Start small. The first record becomes a useful part of your daily system.</p><button className="secondary-button" onClick={() => setEditing("new")}><Plus size={16} /> Add {itemConfig.label}</button></div></div>}</div>{viewing ? <PersonalWorkspace section={section} item={viewing} close={() => setViewing(null)} edit={() => { setViewing(null); setEditing(viewing); }} /> : null}{editing ? <Editor section={section} item={editing === "new" ? null : editing} close={() => setEditing(null)} /> : null}</>;
}

function Card({ item, section, onView, onEdit }: { item: RecordItem; section: Section; onView: () => void; onEdit: () => void }) {
  const client = useQueryClient(); const { toast } = useFeedback(); const path = config[section].path; const title = String(item.title ?? item.name ?? "Untitled"); const detail = String(item.description ?? item.content ?? "No details yet.");
  const remove = useMutation({ mutationFn: () => request(`/api/${path}/${item.id}`, { method: "DELETE" }), onSuccess: () => { client.invalidateQueries({ queryKey: [path] }); toast(`${section === "Knowledge Vault" ? "Entry" : section.slice(0, -1)} deleted`); } }); const check = useMutation({ mutationFn: () => request(`/api/habits/${item.id}/checkin`, { method: item.completedToday ? "DELETE" : "PUT", body: JSON.stringify({}) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["habits"] }); toast(item.completedToday ? "Habit marked open" : "Habit completed"); } });
  return <article className={section === "Habits" ? `task-row premium-row ${item.completedToday ? "completed" : ""}` : "m4-card premium-card"}>{section === "Habits" ? <button className="complete-toggle" onClick={() => check.mutate()}>{item.completedToday ? <CheckCircle2 size={18} /> : null}</button> : null}<button className={section === "Habits" ? "task-main task-open-button" : "card-content-button"} onClick={onView}><div className="title-line"><h2>{title}</h2>{section === "Goals" ? <span className="priority medium">{Number(item.progress ?? 0)}%</span> : <span className="priority low">{String(item.status ?? item.category ?? item.mood ?? section)}</span>}</div><p>{detail}</p>{section === "Goals" && Number(item.linkedTaskCount ?? 0) ? <small className="goal-link-badge">Auto-tracked · {Number(item.completedLinkedTaskCount ?? 0)}/{Number(item.linkedTaskCount)} tasks</small> : null}</button><div className="row-actions"><button aria-label={`Edit ${title}`} onClick={onEdit}><Pencil size={15} /></button><button aria-label={`Delete ${title}`} onClick={() => window.confirm(`Delete ${title}?`) && remove.mutate()}><Trash2 size={15} /></button></div>{section !== "Habits" ? <button className="card-footer" onClick={onView}>View workspace <Target size={15} /></button> : null}</article>;
}

function PersonalWorkspace({ section, item, close, edit }: { section: Section; item: RecordItem; close: () => void; edit: () => void }) {
  const [tab, setTab] = useState("Overview"); const title = String(item.title ?? item.name ?? "Untitled"); const Icon = config[section].icon; const fields = detailsFor(section, item); const summary = section === "Goals" ? `${Number(item.progress ?? 0)}% complete` : section === "Habits" ? item.completedToday ? "Completed today" : "Ready for today" : section === "Journal" ? String(item.entryDate ?? "Today") : String(item.category ?? "General");
  return <div className="workspace-overlay" onMouseDown={close}><aside className="workspace-sheet personal-sheet" onMouseDown={(event) => event.stopPropagation()}><header className="workspace-hero"><button className="back-button" onClick={close}>← Back</button><div className="workspace-hero-top"><span className="workspace-icon"><Icon size={22} /></span><div className="hero-actions"><button className="secondary-button" onClick={edit}><Pencil size={15} /> Edit</button><button className="icon-button" aria-label="Close workspace" onClick={close}><X size={20} /></button></div></div><h1>{title}</h1><p>{summary}</p></header><nav className="workspace-tabs">{["Overview", "Details", "Activity"].map((name) => <button className={tab === name ? "active" : ""} onClick={() => setTab(name)} key={name}>{name}</button>)}</nav><main className="workspace-content">{tab === "Overview" ? <><section className="workspace-stats"><article><span>{section === "Goals" ? "Progress" : "Status"}</span><strong>{summary}</strong></article><article><span>Created</span><strong>{new Date(String(item.createdAt ?? Date.now())).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</strong></article><article><span>Updated</span><strong>{new Date(String(item.updatedAt ?? Date.now())).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</strong></article><article><span>Tags</span><strong>{String(item.tags ?? "—")}</strong></article></section><section className="workspace-panel"><p className="eyebrow">Executive brief</p><h3>{String(item.description ?? item.content ?? "Add the context that makes this useful at a glance.")}</h3></section></> : tab === "Details" ? <EntityDetailsDialog title={title} eyebrow={section} fields={fields} onClose={close} onEdit={edit} /> : <section className="workspace-panel"><p className="eyebrow">Activity</p><h3>This workspace will keep its important updates and completions here.</h3><p>Last updated {new Date(String(item.updatedAt ?? Date.now())).toLocaleString()}.</p></section>}</main></aside></div>;
}
function detailsFor(section: Section, item: RecordItem) { const values = section === "Goals" ? [["Area", item.area], ["Timeframe", item.timeframe], ["Target", item.target], ["Progress", `${item.progress ?? 0}%`], ["Status", item.status], ["Milestones", item.milestones], ["Notes", item.notes]] : section === "Habits" ? [["Frequency", item.frequency], ["Target", item.targetCount], ["Schedule", item.customSchedule], ["Current streak", `${item.currentStreak ?? 0} days`], ["Longest streak", `${item.longestStreak ?? 0} days`], ["Description", item.description]] : section === "Knowledge Vault" ? [["Category", item.category], ["Tags", item.tags], ["Source", item.sourceUrl], ["Knowledge", item.content]] : [["Date", item.entryDate], ["Mood", item.mood], ["Tags", item.tags], ["Reflection", item.content]]; return values.map(([label, value]) => ({ label: String(label), value: value === undefined || value === null ? "" : String(value) })); }

function Editor({ section, item, close }: { section: Section; item: RecordItem | null; close: () => void }) {
  const client = useQueryClient(); const { toast } = useFeedback(); const path = config[section].path; const defaults: Record<string, string> = section === "Goals" ? { title: String(item?.title ?? ""), description: String(item?.description ?? ""), area: String(item?.area ?? "personal"), timeframe: String(item?.timeframe ?? ""), target: String(item?.target ?? ""), progress: String(item?.progress ?? 0), status: String(item?.status ?? "active"), milestones: String(item?.milestones ?? ""), notes: String(item?.notes ?? "") } : section === "Habits" ? { name: String(item?.name ?? ""), description: String(item?.description ?? ""), frequency: String(item?.frequency ?? "daily"), targetCount: String(item?.targetCount ?? 1), customSchedule: String(item?.customSchedule ?? ""), color: String(item?.color ?? "cyan") } : section === "Knowledge Vault" ? { title: String(item?.title ?? ""), content: String(item?.content ?? ""), category: String(item?.category ?? "general"), tags: String(item?.tags ?? ""), sourceUrl: String(item?.sourceUrl ?? "") } : { entryDate: String(item?.entryDate ?? new Date().toISOString().slice(0, 10)), title: String(item?.title ?? ""), content: String(item?.content ?? ""), mood: String(item?.mood ?? "neutral"), tags: String(item?.tags ?? "") };
  const [values, setValues] = useState(defaults); const save = useMutation({ mutationFn: () => request(item ? `/api/${path}/${item.id}` : `/api/${path}`, { method: item ? "PATCH" : "POST", body: JSON.stringify({ ...values, progress: Number(values.progress ?? 0), targetCount: Number(values.targetCount ?? 1) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: [path] }); toast(item ? "Changes saved" : "Added to your workspace"); close(); } }); const input = (name: string, label: string, textarea = false, type = "text") => <label className="field"><span>{label}</span>{textarea ? <textarea rows={3} value={values[name] ?? ""} onChange={(event) => setValues({ ...values, [name]: event.target.value })} /> : <input type={type} value={values[name] ?? ""} onChange={(event) => setValues({ ...values, [name]: event.target.value })} />}</label>;
  return <div className="dialog-backdrop" onMouseDown={close}><div className="dialog" onMouseDown={(event) => event.stopPropagation()}><div className="dialog-header"><div><p className="eyebrow">{section}</p><h2>{item ? "Edit" : "Create"} {config[section].label}</h2></div><button className="icon-button" onClick={close}><X size={19} /></button></div><form onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="form-body">{section === "Goals" ? <>{input("title", "Goal title")}{input("description", "Why it matters", true)}<div className="form-row">{input("area", "Area")}{input("timeframe", "Timeframe")}</div>{input("target", "Target")}{input("progress", "Progress", false, "number")}{input("milestones", "Milestones", true)}{input("notes", "Notes", true)}</> : section === "Habits" ? <>{input("name", "Habit")}{input("description", "Description", true)}<div className="form-row">{input("frequency", "Frequency")}{input("targetCount", "Target", false, "number")}</div>{input("customSchedule", "Custom schedule")}</> : section === "Knowledge Vault" ? <>{input("title", "Title")}{input("content", "Knowledge", true)}<div className="form-row">{input("category", "Category")}{input("tags", "Tags")}</div>{input("sourceUrl", "Source URL")}</> : <>{input("entryDate", "Date", false, "date")}{input("title", "Title")}{input("content", "Reflection", true)}<div className="form-row">{input("mood", "Mood")}{input("tags", "Tags")}</div></>}</div>{save.error ? <p className="form-error">{save.error.message}</p> : null}<div className="dialog-footer"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={save.isPending}>{save.isPending ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />} Save</button></div></form></div></div>;
}
