"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, LoaderCircle, Pencil, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { useFeedback } from "./feedback";

type Section = "Goals" | "Habits" | "Knowledge Vault" | "Journal";
type RecordItem = Record<string, unknown> & { id: string; title?: string; name?: string; content?: string; description?: string; completedToday?: boolean; progress?: number; status?: string; category?: string; mood?: string; tags?: string };
async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "Something went wrong"); } return response.status === 204 ? undefined as T : response.json(); }
const config = { Goals: { path: "goals", label: "goal" }, Habits: { path: "habits", label: "habit" }, "Knowledge Vault": { path: "knowledge", label: "entry" }, Journal: { path: "journal", label: "entry" } } as const;

export function MilestoneFive({ section }: { section: Section }) {
  const [editing, setEditing] = useState<RecordItem | "new" | null>(null); const { path, label } = config[section];
  const query = useQuery({ queryKey: [path], queryFn: () => request<{ goals?: RecordItem[]; habits?: RecordItem[]; entries?: RecordItem[] }>(`/api/${path}`) });
  const items = query.data?.goals ?? query.data?.habits ?? query.data?.entries ?? [];
  return <><div className="page"><div className="page-heading"><div><p className="eyebrow">Personal operating system</p><h1>{section}</h1><p className="subtle">{section === "Goals" ? "Make progress visible and purposeful." : section === "Habits" ? "Build the practices that compound." : section === "Knowledge Vault" ? "Keep valuable ideas easy to rediscover." : "A private space to reflect and retain context."}</p></div><button className="primary-button" onClick={() => setEditing("new")}><Plus size={17} /> New {label}</button></div>{query.isLoading ? <div className="loading-state"><LoaderCircle className="spin" size={20} /> Loading…</div> : query.error ? <div className="error-state">{query.error.message}</div> : items.length ? <div className={section === "Habits" ? "task-list" : "m4-card-grid"}>{items.map((item) => <Card key={item.id} item={item} section={section} edit={() => setEditing(item)} />)}</div> : <div className="large-empty"><div className="empty-state"><h3>No {section.toLowerCase()} yet</h3><p>Capture the first one whenever you are ready.</p><button className="secondary-button" onClick={() => setEditing("new")}><Plus size={16} /> Add {label}</button></div></div>}</div>{editing ? <Editor section={section} item={editing === "new" ? null : editing} close={() => setEditing(null)} /> : null}</>;
}
function Card({ item, section, edit }: { item: RecordItem; section: Section; edit: () => void }) {
  const client = useQueryClient(); const { toast } = useFeedback(); const path = config[section].path; const remove = useMutation({ mutationFn: () => request(`/api/${path}/${item.id}`, { method: "DELETE" }), onSuccess: () => { client.invalidateQueries({ queryKey: [path] }); toast(`${section === "Knowledge Vault" ? "Entry" : section.slice(0, -1)} deleted`); } }); const check = useMutation({ mutationFn: () => request(`/api/habits/${item.id}/checkin`, { method: item.completedToday ? "DELETE" : "PUT", body: JSON.stringify({}) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["habits"] }); toast(item.completedToday ? "Habit marked open" : "Habit completed — nice work"); } });
  const title = String(item.title ?? item.name ?? "Untitled"); const detail = String(item.description ?? item.content ?? "No details yet.");
  return <article className={section === "Habits" ? `task-row ${item.completedToday ? "completed" : ""}` : "m4-card"}>{section === "Habits" ? <button className="complete-toggle" onClick={() => check.mutate()}>{item.completedToday ? <CheckCircle2 size={18} /> : null}</button> : null}<div className="task-main" onClick={edit}><div><h2>{title}</h2>{section === "Goals" ? <span className="priority medium">{Number(item.progress ?? 0)}%</span> : <span className="priority low">{String(item.status ?? item.category ?? item.mood ?? section)}</span>}</div><p>{detail}</p></div><div className="row-actions"><button onClick={edit}><Pencil size={15} /></button><button onClick={() => window.confirm(`Delete ${title}?`) && remove.mutate()}><Trash2 size={15} /></button></div></article>;
}
function Editor({ section, item, close }: { section: Section; item: RecordItem | null; close: () => void }) {
  const client = useQueryClient(); const { toast } = useFeedback(); const path = config[section].path;
  const defaults: Record<string, string> = section === "Goals" ? { title: String(item?.title ?? ""), description: String(item?.description ?? ""), area: String(item?.area ?? "personal"), timeframe: String(item?.timeframe ?? ""), target: String(item?.target ?? ""), progress: String(item?.progress ?? 0), status: String(item?.status ?? "active"), milestones: String(item?.milestones ?? ""), notes: String(item?.notes ?? "") } : section === "Habits" ? { name: String(item?.name ?? ""), description: String(item?.description ?? ""), frequency: String(item?.frequency ?? "daily"), targetCount: String(item?.targetCount ?? 1), customSchedule: String(item?.customSchedule ?? ""), color: String(item?.color ?? "cyan") } : section === "Knowledge Vault" ? { title: String(item?.title ?? ""), content: String(item?.content ?? ""), category: String(item?.category ?? "general"), tags: String(item?.tags ?? ""), sourceUrl: String(item?.sourceUrl ?? "") } : { entryDate: String(item?.entryDate ?? new Date().toISOString().slice(0, 10)), title: String(item?.title ?? ""), content: String(item?.content ?? ""), mood: String(item?.mood ?? "neutral"), tags: String(item?.tags ?? "") };
  const [values, setValues] = useState(defaults); const save = useMutation({ mutationFn: () => request(item ? `/api/${path}/${item.id}` : `/api/${path}`, { method: item ? "PATCH" : "POST", body: JSON.stringify({ ...values, progress: Number(values.progress ?? 0), targetCount: Number(values.targetCount ?? 1) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: [path] }); toast(item ? "Changes saved" : "Added to your workspace"); close(); } }); const input = (name: string, label: string, textarea = false, type = "text") => <label className="field"><span>{label}</span>{textarea ? <textarea rows={3} value={values[name] ?? ""} onChange={(event) => setValues({ ...values, [name]: event.target.value })} /> : <input type={type} value={values[name] ?? ""} onChange={(event) => setValues({ ...values, [name]: event.target.value })} />}</label>;
  return <div className="dialog-backdrop" onMouseDown={close}><div className="dialog" onMouseDown={(event) => event.stopPropagation()}><div className="dialog-header"><div><p className="eyebrow">Milestone 5</p><h2>{item ? "Edit" : "Create"} {config[section].label}</h2></div><button className="icon-button" onClick={close}><X size={19} /></button></div><form onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div className="form-body">{section === "Goals" ? <>{input("title", "Goal title")}{input("description", "Why it matters", true)}<div className="form-row">{input("area", "Area")}{input("timeframe", "Timeframe")}</div>{input("target", "Target")}{input("progress", "Progress", false, "number")}{input("milestones", "Milestones", true)}{input("notes", "Notes", true)}</> : section === "Habits" ? <>{input("name", "Habit")}{input("description", "Description", true)}<div className="form-row">{input("frequency", "Frequency")}{input("targetCount", "Target", false, "number")}</div>{input("customSchedule", "Custom schedule")}</> : section === "Knowledge Vault" ? <>{input("title", "Title")}{input("content", "Knowledge", true)}<div className="form-row">{input("category", "Category")}{input("tags", "Tags")}</div>{input("sourceUrl", "Source URL")}</> : <>{input("entryDate", "Date", false, "date")}{input("title", "Title")}{input("content", "Reflection", true)}<div className="form-row">{input("mood", "Mood")}{input("tags", "Tags")}</div></>}</div>{save.error ? <p className="form-error">{save.error.message}</p> : null}<div className="dialog-footer"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={save.isPending}>{save.isPending ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />} Save</button></div></form></div></div>;
}
