"use client";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowUpRight, UsersRound } from "lucide-react";

type Status = { team: string; openCount: number; overdueCount: number; lastActivity: string | null };
type Team = { id: string; name: string };
async function request<T>(url: string): Promise<T> { const response = await fetch(url); if (!response.ok) throw new Error("Unable to load team health"); return response.json(); }
const relative = (value: string | null) => { if (!value) return "No activity yet"; const hours = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 3600000)); return hours < 1 ? "Updated just now" : hours < 24 ? `Updated ${hours}h ago` : `Updated ${Math.floor(hours / 24)}d ago`; };
export function TeamHealth({ teams, onOpen }: { teams: Team[]; onOpen: (team: Team) => void }) { const query = useQuery({ queryKey: ["team-status"], queryFn: () => request<{ teams: Status[] }>("/api/teams/status") }); const status = query.data?.teams ?? []; return <section className="page team-health-page"><div className="team-health-heading"><div><p className="eyebrow">Council coordination</p><h2><UsersRound size={18} /> Team Health</h2><p>Live council workload, kept separate from your personal plan.</p></div></div><div className="team-health-grid">{status.map((item) => { const team = teams.find((candidate) => candidate.name === item.team); return <button className={`team-health-row ${item.overdueCount ? "at-risk" : ""}`} key={item.team} onClick={() => team && onOpen(team)} disabled={!team}><span><strong>{item.team}</strong><small>{relative(item.lastActivity)}</small></span><span className="team-health-count"><b>{item.openCount}</b> open</span><span className="team-health-count overdue"><b>{item.overdueCount}</b> overdue</span><ArrowUpRight size={17} /></button>; })}</div>{query.error ? <p className="form-error">Unable to refresh team health.</p> : null}</section>; }
