import { z } from "zod";
import { databaseError, supabase } from "../../../db/supabase";

export const dynamic = "force-dynamic";
export const teamSchema = z.object({ name: z.string().trim().min(1, "A team name is required").max(100), description: z.string().trim().max(2000).default(""), members: z.string().trim().max(3000).default(""), responsibilities: z.string().trim().max(3000).default(""), currentProjects: z.string().trim().max(3000).default(""), status: z.enum(["active", "planning", "on_hold"]).default("active"), notes: z.string().trim().max(5000).default(""), color: z.enum(["cyan", "blue", "purple", "amber", "rose", "emerald"]).default("cyan"), icon: z.enum(["layers", "sparkles", "users", "flag", "heart", "book"]).default("layers") });
export function serializeTeam(row: Record<string, unknown>) { return { id:String(row.id), name:String(row.name), description:String(row.description??""), members:String(row.members??""), responsibilities:String(row.responsibilities??""), currentProjects:String(row.current_projects??""), status:String(row.status), notes:String(row.notes??""), color:String(row.color), icon:String(row.icon), archived:Boolean(row.archived), createdAt:String(row.created_at), updatedAt:String(row.updated_at) }; }
export async function createTeamRecord(t: z.infer<typeof teamSchema>) { const {data,error}=await supabase().from("teams").insert({name:t.name,description:t.description,members:t.members,responsibilities:t.responsibilities,current_projects:t.currentProjects,status:t.status,notes:t.notes,color:t.color,icon:t.icon}).select().single(); if(error)throw databaseError(error,"Unable to create team"); return serializeTeam(data as Record<string,unknown>); }

export async function GET() { try { const { data, error } = await supabase().from("teams").select("*").eq("archived", false).order("updated_at", { ascending:false }); if (error) throw databaseError(error,"Unable to load teams"); return Response.json({teams:(data??[]).map(row=>serializeTeam(row as Record<string,unknown>))}); } catch(error) { return Response.json({error:error instanceof Error?error.message:"Unable to load teams"},{status:500}); } }
export async function POST(request:Request) { try { const parsed=teamSchema.safeParse(await request.json()); if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message},{status:400}); return Response.json({team:await createTeamRecord(parsed.data)},{status:201}); } catch(error) { return Response.json({error:error instanceof Error?error.message:"Unable to create team"},{status:500}); } }
