create type public.goal_status as enum ('active', 'completed', 'paused', 'archived');
create type public.habit_frequency as enum ('daily', 'weekly', 'custom');
create type public.journal_mood as enum ('great', 'good', 'neutral', 'low', 'difficult');
create table public.goals (id uuid primary key default gen_random_uuid(), title text not null check (char_length(trim(title)) > 0), description text not null default '', area text not null default 'personal', timeframe text not null default '', target text not null default '', progress smallint not null default 0 check (progress between 0 and 100), status public.goal_status not null default 'active', milestones text not null default '', notes text not null default '', archived boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.habits (id uuid primary key default gen_random_uuid(), name text not null check (char_length(trim(name)) > 0), description text not null default '', frequency public.habit_frequency not null default 'daily', target_count smallint not null default 1 check (target_count between 1 and 100), custom_schedule text not null default '', color text not null default 'cyan' check (color in ('cyan', 'blue', 'purple', 'amber', 'rose', 'emerald')), archived boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.habit_checkins (id uuid primary key default gen_random_uuid(), habit_id uuid not null references public.habits(id) on delete cascade, completed_on date not null, quantity smallint not null default 1 check (quantity between 1 and 100), note text not null default '', created_at timestamptz not null default timezone('utc', now()), unique (habit_id, completed_on));
create table public.knowledge_entries (id uuid primary key default gen_random_uuid(), title text not null check (char_length(trim(title)) > 0), content text not null default '', category text not null default 'general', tags text not null default '', source_url text not null default '', archived boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table public.journal_entries (id uuid primary key default gen_random_uuid(), entry_date date not null default current_date, title text not null default '', content text not null check (char_length(trim(content)) > 0), mood public.journal_mood not null default 'neutral', tags text not null default '', archived boolean not null default false, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create index goals_active_updated_idx on public.goals (updated_at desc) where not archived;
create index habits_active_updated_idx on public.habits (updated_at desc) where not archived;
create index habit_checkins_habit_date_idx on public.habit_checkins (habit_id, completed_on desc);
create index knowledge_entries_active_updated_idx on public.knowledge_entries (updated_at desc) where not archived;
create index journal_entries_active_date_idx on public.journal_entries (entry_date desc) where not archived;
create trigger goals_set_updated_at before update on public.goals for each row execute function public.set_updated_at();
create trigger habits_set_updated_at before update on public.habits for each row execute function public.set_updated_at();
create trigger knowledge_entries_set_updated_at before update on public.knowledge_entries for each row execute function public.set_updated_at();
create trigger journal_entries_set_updated_at before update on public.journal_entries for each row execute function public.set_updated_at();
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.habit_checkins enable row level security;
alter table public.knowledge_entries enable row level security;
alter table public.journal_entries enable row level security;
